### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by agersoncgps** [CodingZeal/react-native-appstate-listener#4]
Works like a dream on iOS, doesn't appear to respond on Android. Is Android supported?

**Comment by randycoulman** [comment]
This library is a thin wrapper around react-native's [AppState API](https://facebook.github.io/react-native/docs/appstate.html), so it should work everywhere that does.  I don't see anything in the docs that suggest that it's iOS only, so Android should be supported.

If you try running the `AppState` example from the react-native docs on Android, does it work for you?

**Comment by randycoulman** [comment]
Closing.  If you find that this is not working on Android, please open a new issue with additional details.  Thanks!
